import {
  LayoutDashboard,
  ShoppingCart,
  AlertTriangle,
  TicketPercent,
  Sparkles,
  Table,
  CreditCard,
  Folder,
  FileSpreadsheet,
  FileText,
  Landmark,
  Warehouse,
  ChefHat,
  Truck,
  FileBarChart,
} from "lucide-react";
import DashboardLayout, { DashboardMenuEntry } from "@/components/DashboardLayout";

const adminMenuItems: DashboardMenuEntry[] = [
  { type: "section", label: "OPERAÇÃO" },
  { icon: LayoutDashboard, label: "Dashboard", path: "/admin" },
  { icon: ShoppingCart, label: "Pedidos", path: "/orders" },
  { icon: CreditCard, label: "Pagamentos", path: "/payments" },
  { icon: AlertTriangle, label: "Alertas", path: "/stock-alerts" },
  { icon: Sparkles, label: "Fidelidade", path: "/loyalty" },
  { icon: TicketPercent, label: "Cupons", path: "/coupons" },
  { icon: Table, label: "Mesas", path: "/tables" },
  {
    icon: Folder,
    label: "Cadastro",
    path: "/cadastro",
    children: [
      { label: "Produto", path: "/cadastro/produto" },
      { label: "Participante", path: "/cadastro/participante" },
      { label: "Fiscal", path: "/cadastro/fiscal" },
      { label: "Financeiro", path: "/cadastro/financeiro" },
      { label: "Caixa Venda", path: "/cadastro/caixa-venda" },
      { label: "Usuário", path: "/cadastro/usuario" },
      { label: "Veículo", path: "/cadastro/veiculo" },
      { label: "Setor", path: "/cadastro/setor" },
    ],
  },
  {
    icon: FileSpreadsheet,
    label: "Faturamento",
    path: "/faturamento",
    children: [
      { label: "Notas Fiscais Eletrônicas", path: "/faturamento/notas-fiscais-eletronicas" },
      { label: "Notas Fiscais de Serviço", path: "/faturamento/notas-fiscais-servico" },
      { label: "Manifesto de Documentos", path: "/faturamento/manifesto-documentos" },
      { label: "Conhecimento de Transporte", path: "/faturamento/conhecimento-transporte" },
      { label: "Conhecimento de Transporte - OS", path: "/faturamento/conhecimento-transporte-os" },
      { label: "Orçamento", path: "/faturamento/orcamento" },
      { label: "Condicional", path: "/faturamento/condicional" },
      { label: "Pedido de Venda", path: "/faturamento/pedido-venda" },
      { label: "Ordem de Serviço", path: "/faturamento/ordem-servico" },
      { label: "Venda Futura/Retiradas", path: "/faturamento/venda-futura-retiradas" },
      { label: "Venda Externa/Retorno", path: "/faturamento/venda-externa-retorno" },
      { label: "Geração/Reajuste Contrato", path: "/faturamento/geracao-reajuste-contrato" },
      { label: "Romaneiro de Carga/Entrega", path: "/faturamento/romaneiro-carga-entrega" },
      { label: "Importação XML NFe/NFCe/CTe", path: "/faturamento/importacao-xml-nfe-nfce-cte" },
    ],
  },
  {
    icon: CreditCard,
    label: "PDV",
    path: "/pdv",
    children: [
      { label: "Caixa", path: "/pdv/caixa" },
      { label: "Vendas", path: "/pdv/vendas" },
      { label: "Configuração", path: "/pdv/configuracao" },
    ],
  },
  {
    icon: FileText,
    label: "Entrada de Nota",
    path: "/entrada-nota",
    children: [
      { label: "Cadastrar", path: "/entrada-nota/cadastrar" },
      { label: "Consultar", path: "/entrada-nota/consultar" },
      { label: "Importação XML", path: "/entrada-nota/importacao-xml" },
      { label: "Tributação NFe Entrada", path: "/entrada-nota/tributacao-nfe-entrada" },
    ],
  },
  {
    icon: FileText,
    label: "Documentos Recebidos",
    path: "/documentos-recebidos",
    children: [
      { label: "Consulta NFe's Recebidas", path: "/documentos-recebidos/consulta-nfes-recebidas" },
      { label: "Consulta CTe's Recebidas", path: "/documentos-recebidos/consulta-ctes-recebidas" },
      { label: "Importação NFe's Recebidas", path: "/documentos-recebidos/importacao-nfes-recebidas" },
      { label: "Importação CTe's Recebidas", path: "/documentos-recebidos/importacao-ctes-recebidas" },
      { label: "Eventos Vinculados as NFe's", path: "/documentos-recebidos/eventos-vinculados-nfes" },
      { label: "Manifestação NFe's Usuário", path: "/documentos-recebidos/manifestacao-nfes-usuario" },
    ],
  },
  {
    icon: FileText,
    label: "Pedido de Compra",
    path: "/pedido-compra",
    children: [
      { label: "Cadastrar", path: "/pedido-compra/cadastrar" },
      { label: "Consultar", path: "/pedido-compra/consultar" },
      { label: "Cotação", path: "/pedido-compra/cotacao" },
    ],
  },
  {
    icon: FileText,
    label: "Assinador",
    path: "/assinador",
    children: [
      { label: "Painel de Assinaturas", path: "/assinador/painel-assinaturas" },
    ],
  },
  {
    icon: Landmark,
    label: "Financeiro",
    path: "/financeiro",
    children: [
      { label: "Caixa", path: "/financeiro/caixa" },
      { label: "Lançamento Financeiro", path: "/financeiro/lancamento-financeiro" },
      { label: "Consulta Lançamentos", path: "/financeiro/consulta-lancamentos" },
      { label: "Recebimento de Cartões", path: "/financeiro/recebimento-cartoes" },
      { label: "Lançamento Recorrentes", path: "/financeiro/lancamentos-recorrentes" },
      { label: "Contas em Aberto de Clientes", path: "/financeiro/contas-aberto-clientes" },
      { label: "Contas em Aberto por Documentos", path: "/financeiro/contas-aberto-documentos" },
      { label: "Boletos", path: "/financeiro/boletos" },
      { label: "Custo Fixo", path: "/financeiro/custo-fixo" },
      { label: "Extrato Bancario", path: "/financeiro/extrato-bancario" },
      { label: "Controle de Cheques", path: "/financeiro/controle-cheques" },
      { label: "Movimentações entre Contas", path: "/financeiro/movimentacoes-entre-contas" },
      { label: "Consulta Transações/Integrações", path: "/financeiro/consulta-transacoes-integracoes" },
    ],
  },
  {
    icon: FileText,
    label: "Fiscal",
    path: "/fiscal",
    children: [
      { label: "Lançamentos", path: "/fiscal/lancamentos" },
      { label: "Arquivos Fiscais", path: "/fiscal/arquivos-fiscais" },
      { label: "Registro de Inventário", path: "/fiscal/registro-inventario" },
      { label: "Gestão de Documentos", path: "/fiscal/gestao-documentos" },
    ],
  },
  {
    icon: Warehouse,
    label: "Estoque",
    path: "/estoque",
    children: [
      { label: "Entradas", path: "/estoque/entradas" },
      { label: "Entradas e Saídas", path: "/estoque/entradas-saidas" },
      { label: "Entradas e Saídas Detalhado", path: "/estoque/entradas-saidas-detalhado" },
      { label: "Curva ABC", path: "/estoque/curva-abc" },
      { label: "Últimas Vendas", path: "/estoque/ultimas-vendas" },
      { label: "Estoque Sintético", path: "/estoque/estoque-sintetico" },
      { label: "Lucro de Estoque", path: "/estoque/lucro-estoque" },
      { label: "Tabela de Preços", path: "/estoque/tabela-precos" },
      { label: "Giro de Mercadoria", path: "/estoque/giro-mercadoria" },
      { label: "Lançar Estoque Inicial", path: "/estoque/lancar-estoque-inicial" },
      { label: "Quantidade de Estoque", path: "/estoque/quantidade-estoque" },
      { label: "Estoque por Localização", path: "/estoque/estoque-por-localizacao" },
      { label: "Estoque Minimo/Máximo", path: "/estoque/estoque-minimo-maximo" },
      { label: "Posição Atual do Estoque", path: "/estoque/posicao-atual" },
      { label: "Ajuste de Estoque por Produto", path: "/estoque/ajuste-por-produto" },
      { label: "Quantidade em Estoque/Grade", path: "/estoque/quantidade-grade" },
      { label: "Contagem Estoque/Ajuste de Estoque", path: "/estoque/contagem-ajuste" },
    ],
  },
  {
    icon: ChefHat,
    label: "Produção",
    path: "/producao",
    children: [
      { label: "Cadastrar", path: "/producao/cadastrar" },
      { label: "Consultar", path: "/producao/consultar" },
      { label: "Gerar Produção", path: "/producao/gerar-producao" },
      { label: "Tipo de Matéria Prima", path: "/producao/tipo-materia-prima" },
      { label: "Consultar Produções Geradas", path: "/producao/consultar-producoes-geradas" },
    ],
  },
  {
    icon: Truck,
    label: "Delivery",
    path: "/delivery",
    children: [
      { label: "Delivery", path: "/delivery/delivery" },
      { label: "Entregador", path: "/delivery/entregador" },
      { label: "Gerar QR Code Delivery", path: "/delivery/gerar-qr-code" },
    ],
  },
  {
    icon: FileBarChart,
    label: "Relatórios",
    path: "/relatorios",
    children: [
      { label: "Log do Sistema", path: "/relatorios/log-sistema" },
      { label: "Relatórios Gerenciais", path: "/relatorios/relatorios-gerenciais" },
      { label: "Lanças Previsão DRE", path: "/relatorios/lancas-previsao-dre" },
      { label: "Gerador de Relatórios", path: "/relatorios/gerador-relatorios" },
      { label: "Relatório envio WhatsApp", path: "/relatorios/envio-whatsapp" },
      { label: "Notas Fiscais de Saída", path: "/relatorios/notas-fiscais-saida" },
      { label: "Notas Fiscais De Entrada", path: "/relatorios/notas-fiscais-entrada" },
      { label: "Notas Fiscais de Serviço", path: "/relatorios/notas-fiscais-servico" },
      { label: "Conhecimentos Eletrônicos", path: "/relatorios/conhecimentos-eletronicos" },
      { label: "Manifesto de Documentos", path: "/relatorios/manifesto-documentos" },
      { label: "Notas Fiscais do Consumidor", path: "/relatorios/notas-fiscais-consumidor" },
      { label: "Produtos", path: "/relatorios/produtos" },
      { label: "Financeiro", path: "/relatorios/financeiro" },
      { label: "Orçamento", path: "/relatorios/orcamento" },
      { label: "Livros Fiscais", path: "/relatorios/livros-fiscais" },
      { label: "Venda Externa", path: "/relatorios/venda-externa" },
      { label: "Pedido de Venda", path: "/relatorios/pedido-venda" },
      { label: "Ordens de Serviço", path: "/relatorios/ordens-servico" },
      { label: "Lucro de Venda/Comissões/Outros", path: "/relatorios/lucro-venda-comissoes-outros" },
    ],
  },
];

export default function AdminLayout({ children }: { children: React.ReactNode }) {
  return <DashboardLayout menuItems={adminMenuItems}>{children}</DashboardLayout>;
}
